version: '3.9'

services:
  postgres:
    build: ./postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meubanco
    networks:
      - app-network

  mongodb:
    build: ./mongodb
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - app-network

  nodejs:
    build: ./nodejs
    container_name: nodejs_container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
